---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo-headers
  labels:
    tier: api
    component: nginx-echo-headers
    {{- (include "common_labels" .) | indent 4 }}
spec:
  selector:
    matchLabels:
      tier: api
      component: nginx-echo-headers
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.echo_headers.replicas }}
  template:
    metadata:
      labels:
        tier: api
        component: nginx-echo-headers
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      {{- (include "affinity_requirements" .) | indent 6 }}
      containers:
        - name: nginx-echo-headers
          image: {{ .Values.echo_headers.image }}
          resources:
            requests:
              cpu: {{ .Values.echo_headers.requests.cpu }}
              memory: {{ .Values.echo_headers.requests.memory }}
          ports:
            - containerPort: {{ .Values.echo_headers.port }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: nodeport-nginx-echo-headers
  labels:
    tier: api
    component: nginx-echo-headers
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.echo_headers.port }}
  selector:
    tier: api
    component: nginx-echo-headers
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
