---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      tier: backend
      component: redis
      {{- (include "common_labels" .) | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
        component: redis
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      {{- (include "affinity_requirements" .) | indent 6 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.redis.requests.memory }}
              cpu: {{ .Values.redis.requests.cpu }}
          ports:
            - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: redis
  labels:
    tier: backend
    component: redis
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
  selector:
    tier: backend
    component: redis
    {{- (include "common_labels" .) | indent 4 }}
