apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hq-deployment
  labels:
    environment: production
    tier: api
    app: hq-deployment
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.static_ip_name | quote}}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.ingress.pre_shared_cert | quote }}
    kubernetes.io/ingress.allow-http: {{ .Values.ingress.allow_http | quote }}
spec:
  rules:
    # Registry API rules
    - host: registry.api.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-registry
              port:
                number: {{ .Values.registry.port }}
          pathType: ImplementationSpecific
    # MIR ID Controller API Service rules
    - host: mirid.api.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-mirid-controller
              port:
                number: {{ .Values.mirid_controller.port }}
          pathType: ImplementationSpecific
    # Registry Web Frontend rules
    - host: registry.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-web-hq
              port:
                number: {{ .Values.frontend.port }}
          pathType: ImplementationSpecific
    # Accounts web
    - host: auth.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-keycloak
              port:
                number: {{ .Values.keycloak.port }}
          pathType: ImplementationSpecific
    # Testing endpoint
    - host: echo.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-nginx-echo-headers
              port:
                number: {{ .Values.echo_headers.port }}
          pathType: ImplementationSpecific
